name: Version bump required

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]


jobs:
  check-version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compare versions
        run: |
          git fetch origin main
          OLD_VERSION=$(git show origin/main:pyproject.toml | grep '^version =' | cut -d'=' -f2)
          NEW_VERSION=$(grep '^version =' pyproject.toml | cut -d'=' -f2)

          echo "OLD_VERSION=$OLD_VERSION"
          echo "NEW_VERSION=$NEW_VERSION"

          if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
            echo "❌ You must bump version in pyproject.toml for this PR"
            exit 1
          fi

          echo "✅ Version bumped."
